# Input buffer keys
P_MASS_KEY = "particleMass"
P_POS_KEY = "particlePosition"
P_VEL_KEY = "particleVelocity"
P_DISP_KEY = "particleDisplacement"
P_RADIUS_KEY = "particleRadius"
C_POS_KEY = "contactPosition"
C_TANGENT_U_KEY = "contactTangentU"
C_TANGENT_V_KEY = "contactTangentV"
C_NORMAL_KEY = "contactNormal"
C_FORCE_KEY = "localContactForce"
C_DISTANCE_KEY = "contactDistanceVector"

# Output buffers keys
F_MASS_DENSITY_KEY = "massDensity"
F_MOM_DENSITY_KEY = "momentumDensity"
F_VEL_KEY = "velocity"
F_DISP_KEY = "displacement"
F_GRANULAR_TEMP_KEY = "granularTemperature"
F_STRESS_KEY = "stressTensor"
F_PRESSURE_KEY = "pressure"
F_VON_MISES_KEY = "vonMisesStress"
F_STRAIN_KEY = "strainTensor"
F_RATE_OF_STRAIN_KEY = "rateOfStrainTensor"
S_MEAN_DIAMETER_KEY = "meanParticleDiameter"
